[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/models/*"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For Single Page Apps (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200